config/routes.rb
Test1::Application.routes.draw do
  resources :question_responses

end

app/models/question_response.rb
class QuestionResponse < ActiveRecord::Base
  has_many :question_response_options
  has_many :survey_options, :through => :question_response_options
  belongs_to :survey_question
  
  attr_accessible :survey_option_ids
end

app/models/question_response_option.rb
class QuestionResponseOption < ActiveRecord::Base
  belongs_to :question_response
  belongs_to :survey_option
end

app/models/survey_option.rb
class SurveyOption < ActiveRecord::Base
  belongs_to :survey_question
  # attr_accessible :title, :body
end

app/models/survey_question.rb
class SurveyQuestion < ActiveRecord::Base
  has_many :survey_options
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/question_responses_controller.rb
class QuestionResponsesController < ApplicationController
  # GET /question_responses
  # GET /question_responses.json
  def index
    @question_responses = QuestionResponse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @question_responses }
    end
  end

  # GET /question_responses/1
  # GET /question_responses/1.json
  def show
    @question_response = QuestionResponse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question_response }
    end
  end

  # GET /question_responses/new
  # GET /question_responses/new.json
  def new
    @question_response = QuestionResponse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question_response }
    end
  end

  # GET /question_responses/1/edit
  def edit
    @question_response = QuestionResponse.find(params[:id])
  end

  # POST /question_responses
  # POST /question_responses.json
  def create
    @question_response = QuestionResponse.new(params[:question_response])

    respond_to do |format|
      if @question_response.save
        format.html { redirect_to @question_response, notice: 'Question response was successfully created.' }
        format.json { render json: @question_response, status: :created, location: @question_response }
      else
        format.html { render action: "new" }
        format.json { render json: @question_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /question_responses/1
  # PUT /question_responses/1.json
  def update
    @question_response = QuestionResponse.find(params[:id])

    respond_to do |format|
      if @question_response.update_attributes(params[:question_response])
        format.html { redirect_to @question_response, notice: 'Question response was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question_response.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /question_responses/1
  # DELETE /question_responses/1.json
  def destroy
    @question_response = QuestionResponse.find(params[:id])
    @question_response.destroy

    respond_to do |format|
      format.html { redirect_to question_responses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_responses_helper.rb
module QuestionResponsesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/question_responses/_form.html.erb
<%= semantic_form_for(@question_response) do |f| %>
  <% if @question_response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_response.errors.count, "error") %> prohibited this question_response from being saved:</h2>

      <ul>
      <% @question_response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs do %>
    <%= f.input :survey_options, :as => :check_boxes, collection: f.object.survey_question.survey_options %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_responses/edit.html.erb
<h1>Editing question_response</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_response %> |
<%= link_to 'Back', question_responses_path %>

app/views/question_responses/index.html.erb
<h1>Listing question_responses</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @question_responses.each do |question_response| %>
  <tr>
    <td><%= link_to 'Show', question_response %></td>
    <td><%= link_to 'Edit', edit_question_response_path(question_response) %></td>
    <td><%= link_to 'Destroy', question_response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question response', new_question_response_path %>

app/views/question_responses/new.html.erb
<h1>New question_response</h1>

<%= render 'form' %>

<%= link_to 'Back', question_responses_path %>

app/views/question_responses/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_question_response_path(@question_response) %> |
<%= link_to 'Back', question_responses_path %>